name: Go

on:
  push:
    branches: [ "exp" ]
  pull_request:
    branches: [ "exp" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: JobBuddyEnv

    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}


    steps:
    - uses: actions/checkout@v4

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib

    - name: Start PostgreSQL service
      run: sudo service postgresql start


    - name: Set up PostgreSQL user and database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE job_buddy;"

    - name: Set environment variables for PostgreSQL
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> $GITHUB_ENV
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> $GITHUB_ENV


    - name: Install dependencies
      run: go mod download

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Migrate
      run: go run ./cmd/migration/

    - name: Test
      run: go test -v ./tests/...
