name: Go

on:
  push:
    branches: [ "exp" ]
  pull_request:
    branches: [ "exp" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: JobBuddyEnv

    env:
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}

    steps:
    - uses: actions/checkout@v4

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib

    - name: Start PostgreSQL service
      run: sudo service postgresql start

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready --host=$DATABASE_HOST --port=$DATABASE_PORT --username=$DATABASE_USERNAME; do
          sleep 1
        done

    - name: Set up PostgreSQL database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE $DATABASE_NAME;"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;"

    - name: Install dependencies
      run: go mod download

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Migrate
      run: go run ./cmd/migration/

    - name: Test
      run: go test -v ./tests/...
